# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2022

steps:
  - task: UseDotNet@2
    displayName: Use .NET 
    inputs: 
      packageType: 'sdk'
      version: 7.x
      vsVersion: 17.4.x