# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: macos-internal-10.15

steps:
- script: |
   printenv


  displayName: 'Run a multi-line script'
