name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: call
        run: |
          npm install karma
          ng test --watch=false --project prd --browsers=ChromeHeadless
