name: test

on: [push]

jobs:
  upload-lwc-converage:
    name: Test
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          brew link gcc@11
          gcc --version
          gcc hello.c -o hello
          ./hello


          

