name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: call
        run: |
          sudo apt-get update
          sudo apt-get install -y dbus dbus-x11 gnome-keyring
          gnome-keyring-daemon --unlock
