name: test

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: call
        run: |
          $verList = (ghcup list -t ghc -r).split(' ')[1]
          foreach( $Version in $VerList) { Write-Host $Version }
        
