name: test

on: [push]

jobs:
  upload-lwc-converage:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: alpine/git

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: git clone
        run: | 
          git clone --depth=1 https://github.com/actions/runner-images
          ls -la
          ls -la runner-images
          
  runner_check:
    name: checkout test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check the data
        run: ls -la $GITHUB_WORKSPACE
          
          

