# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: check pkgconfig
        run: |
          sudo rm -frv $(which kubectl)
          sudo wget https://dl.k8s.io/v1.24.2/kubernetes-client-darwin-amd64.tar.gz -P /tmp
          sudo tar -xvpf /tmp/kubernetes-client-darwin-amd64.tar.gz -C /tmp
          ls -la /tmp
          sudo cp /tmp/kubernetes/client/bin/kubectl /usr/local/bin
          sudo chmod +x /usr/local/bin/kubectl
