name: Screencapture

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  latest:
    runs-on: macos-latest

    steps:
    - run: screencapture -T30 -V 30 foo.mov
    - uses: actions/upload-artifact@v3
      with:
        name: latest
        path: foo.mov
