name: test

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: call
        run: |
          curl https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.31-winx64.zip
        
