name: test

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: call
        run: |
          $crudeList = ghcup list -t ghc -r
          $crudeList.split(' ')[2]
        
