name: test

on: [push]

jobs:
  upload-lwc-converage:
    name: Test
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          which python3


          

