name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: call
        run: |
          npm i @angular/cli
          ng new angular-tour-of-heroes
          ng test --watch=false --browsers=ChromeHeadless
