name: test

on: [push]

jobs:
  upload-lwc-converage:
    name: Test
    runs-on: windows-2022

    steps:
      - name: test
        run: |
          wsl --update
          wsl --set-default-version 1
          wsl --status


          

