name: test

on: [push]

jobs:
  upload-lwc-converage:
    name: Test
    runs-on: macos-11

    steps:
      - name: test
        run: |
          file /Library/Frameworks/Python.framework/Versions/Current/bin


          

