name: test

on: [push]

jobs:
  upload-lwc-converage:
    name: Test
    runs-on: windows-2019

    steps:
      - name: test
        run: choco install postgresql -y --params '/Password:root /NoPath' --params-global --version=14.6.1

          

